// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rise.Task.Contact.Db;

#nullable disable

namespace Rise.Task.Contact.Db.Migrations
{
    [DbContext(typeof(ContactDbContext))]
    partial class ContactDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rise.Task.Contact.Domain.Aggregate.AddressModel", b =>
                {
                    b.Property<int>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UUID"));

                    b.Property<int>("ContactUUID")
                        .HasColumnType("integer");

                    b.Property<string>("Iletisim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IletisimTipi")
                        .HasColumnType("integer");

                    b.HasKey("UUID");

                    b.HasIndex("ContactUUID");

                    b.ToTable("Addresses", (string)null);
                });

            modelBuilder.Entity("Rise.Task.Contact.Domain.Aggregate.ContactModel", b =>
                {
                    b.Property<int>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UUID"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Firma")
                        .HasColumnType("text");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UUID");

                    b.ToTable("Contacts", (string)null);
                });

            modelBuilder.Entity("Rise.Task.Contact.Domain.Aggregate.ReportModel", b =>
                {
                    b.Property<int>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UUID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<bool>("IsReady")
                        .HasColumnType("boolean");

                    b.HasKey("UUID");

                    b.ToTable("Reports", (string)null);
                });

            modelBuilder.Entity("Rise.Task.Contact.Domain.Aggregate.AddressModel", b =>
                {
                    b.HasOne("Rise.Task.Contact.Domain.Aggregate.ContactModel", "Contact")
                        .WithMany("Addresses")
                        .HasForeignKey("ContactUUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("Rise.Task.Contact.Domain.Aggregate.ContactModel", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
